{{- if .Values.secretReader.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-image-swapper.fullname" . }}
  labels:
    {{- include "k8s-image-swapper.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    {{- if .Values.secretReader.secretNames }}
    resourceNames:
      {{- toYaml .Values.secretReader.secretNames | nindent 6 }}
    {{- end }}
    verbs:
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
{{- end }}
