{{- if .Values.secretReader.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-image-swapper.fullname" . }}
  labels:
    {{- include "k8s-image-swapper.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-image-swapper.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-image-swapper.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
