apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-image-swapper.fullname" . }}
  labels:
    {{- include "k8s-image-swapper.labels" . | nindent 4 }}
data:
{{- if .Values.config }}
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
{{- end }}
