apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-image-swapper.fullname" . }}
  labels:
    {{- include "k8s-image-swapper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "k8s-image-swapper.selectorLabels" . | nindent 4 }}
