name: Update helm-docs

on: pull_request

env:
  HELM_DOCS_VERSION: "1.11.0"

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install binaries
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v${{env.HELM_DOCS_VERSION}}/helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz | tar xvfz - --overwrite -C $GITHUB_WORKSPACE/bin

    - run: helm-docs

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: 'charts/**/README.md'
        commit_message: 'docs: update helm-docs'
