{{- if .Values.patch.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s-image-swapper.fullname" . }}-patch-create
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "k8s-image-swapper.labels" . | nindent 4 }}
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
      name: {{ include "k8s-image-swapper.serviceAccountName" . }}-create
{{- with .Values.patch.podAnnotations }}
      annotations:
{{ toYaml .  | indent 8 }}
{{- end }}
      labels:
        {{- include "k8s-image-swapper.labels" . | nindent 8 }}
    spec:
      {{- if .Values.patch.priorityClassName }}
      priorityClassName: {{ .Values.patch.priorityClassName }}
      {{- end }}
      containers:
        - name: create
          {{- if .Values.patch.image.sha }}
          image: {{ .Values.patch.image.repository }}:{{ .Values.patch.image.tag }}@sha256:{{ .Values.patch.image.sha }}
          {{- else }}
          image: {{ .Values.patch.image.repository }}:{{ .Values.patch.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.patch.image.pullPolicy }}
          args:
            - create
            - --host={{ template "k8s-image-swapper.fullname" . }},{{ template "k8s-image-swapper.fullname" . }}.{{ .Release.Namespace }}.svc
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ template "k8s-image-swapper.fullname" . }}
          resources:
{{ toYaml .Values.patch.resources | indent 12 }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "k8s-image-swapper.fullname" . }}-patch
      {{- with .Values.patch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.patch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.patch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
{{- end }}
